# image: gcr.io/heptio-images/ks-guestbook-demo:0.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shantelle-guestbook
  template:
    metadata:
      labels:
        app: shantelle-guestbook
    spec:
      containers:
      - image: docker.io/xrlim/simple-app:latest
        name: shantelle-guestbook
        ports:
        - containerPort: 80
